services:
  - type: web
    name: server-polling
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: FLASK_APP
        value: app
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: "10000"
    plan: free 